spring.application.name=QuizService

spring.datasource.url=
spring.datasource.username=postgres
spring.datasource.password=JQ%UF^_3sw7h$?G
# spring.datasource.driver-class-name=org.postgresql.Driver

# JPA configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.com.example.demo=INFO
spring.jpa.properties.hibernate.format_sql=true