# spring.application.name=ApiGateway
# server.port=8084


# spring.cloud.gateway.routes[0].id=QUIZSERVICE
# spring.cloud.gateway.routes[0].uri=lb://QUIZSERVICE
# spring.cloud.gateway.routes[0]=path=/quiz/**


# eureka.client.service-url.defaultZone=http://localhost:8083/eureka/

spring.application.name=ApiGateway
server.port=8084

# Corrected Route for Quiz Service
spring.cloud.gateway.routes[0].id=QuizService
spring.cloud.gateway.routes[0].uri=lb://QuizService
spring.cloud.gateway.routes[0].predicates[0]=Path=/quiz/**

eureka.client.service-url.defaultZone=http://localhost:8083/eureka/
